In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

# データをコード内に直接定義（例）
# X0, X1, X2, X3が説明変数、Yが目的変数
# 下記はサンプルであり、実際の値に合わせて変更してください
X = np.array([
    [7, 4, 8, 5],
    [7, 10, 3, 7],
    [8, 5, 4, 8],
    [6, 5, 9, 2],
    [6, 5, 2, 10],
    [6, 10, 8, 4]
])

Y = np.array([108, 100, 72, 120, 54, 102])  # こちらもサンプル値

# 線形回帰モデルの作成・学習
model = LinearRegression()
model.fit(X, Y)

# 結果表示
print("回帰係数 (coefs):", model.coef_)
print("切片 (intercept):", model.intercept_)
print("決定係数 (R^2):", model.score(X, Y))

# 予測例
X_new = np.array([[7, 5, 8, 5]])  # 新しい入力例
Y_pred = model.predict(X_new)
print("新しい入力に対する予測値:", Y_pred[0])


回帰係数 (coefs): [  4.93818107   0.57959853  -2.89217534 -11.14317902]
切片 (intercept): 139.22613682916835
決定係数 (R^2): 0.9075168189948278
新しい入力に対する予測値: 97.83809913969685


In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression

np.random.seed(42)  # 再現性確保のための乱数シード設定(任意)

N = 500  # データ数

# X0, X1, X2, X3をランダムに生成（-10～10までの一様分布など）
X0 = np.random.uniform(-10, 10, N)
X1 = np.random.uniform(-10, 10, N)
X2 = np.random.uniform(-10, 10, N)
X3 = np.random.uniform(-10, 10, N)

# 与えられた式に従ってYを計算
Y = X0 * X1 + 0.1 * X1 * X2 * X3 + X2**2

# 必要に応じてXとYをまとめたデータセットとして扱うことができます
# 例えば、XをN行4列の行列、YをN行1列のベクトルとして格納する
X = np.column_stack([X0, X1, X2, X3])

# XとYの一部を出力確認
print("Xの一部:\n", X[:5])
print("Yの一部:\n", Y[:5])
print("生成されたデータ数:", len(Y))

# 目的の形 X0*X1 + 0.1*X1*X2*X3 + X2^2 を近似できるような特徴量を生成
F1 = X[:,0] * X[:,1]        # X0*X1
F2 = X[:,1] * X[:,2] * X[:,3] # X1*X2*X3
F3 = X[:,2]**2              # X2^2

# 新しい特徴行列を作成
F = np.column_stack([F1, F2, F3])

# 線形回帰モデルを作成
model = LinearRegression()
model.fit(F, Y)

# 結果表示
print("回帰係数:", model.coef_)      # [a, b, c]に相当
print("切片:", model.intercept_)
print("決定係数 (R^2):", model.score(F, Y))

# 学習されたモデルは Y ≈ intercept + a*(X0X1) + b*(X1X2X3) + c*(X2^2) の形
# ここで、0.1*(X1X2X3)のような固定係数は学習によって決定されます。
# もし0.1など係数を固定したい場合は、係数を固定して残りをフィットするような工夫が必要です。

# 新しいデータ点に対する予測例
X_new = np.array([[7,4,8,5]]) # 1点のみの例
F_new = np.column_stack([
    X_new[:,0]*X_new[:,1],
    X_new[:,1]*X_new[:,2]*X_new[:,3],
    X_new[:,2]**2
])
Y_pred = model.predict(F_new)
print("新しい入力に対する予測値:", Y_pred[0])


Xの一部:
 [[-2.50919762  3.96323428 -6.29734142  0.3816357 ]
 [ 9.01428613  0.72192733  0.83801895 -0.41636245]
 [ 4.63987884 -3.80944767  7.45891672 -9.48715868]
 [ 1.97316968  6.27590039  4.64449773 -3.17504345]
 [-6.87962719  3.69462345  6.13122296 -2.39608762]]
Yの一部:
 [28.75949071  7.18474578 64.91721048 24.70003028  6.7465111 ]
生成されたデータ数: 500
回帰係数: [1.  0.1 1. ]
切片: 0.0
決定係数 (R^2): 1.0
新しい入力に対する予測値: 108.0
